[package]
authors = ["Misha Tavkhelidze <misha.tavkhelidze@gmail.com>"]
description = "Misha's echo"
edition = "2021"
license = "MIT"
name = "mrecho"
version = "0.1.0"

[dependencies]
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
